DROP TABLE IF EXISTS `pnad_trimensal`;

CREATE TABLE `pnad_trimensal` (
	`Ano` VARCHAR(4) NULL COMMENT 'Ano de referência',
	`Trimestre` VARCHAR(1) NULL COMMENT 'Trimestre de referência',
	`UF` VARCHAR(2) NULL COMMENT 'Unidade da Federação',
	`Capital` VARCHAR(2) NULL COMMENT 'Município da Capital',
	`RM_RIDE` VARCHAR(2) NULL COMMENT 'Reg. Metr. e Reg. Adm. Int. Des.',
	`UPA` VARCHAR(9) NULL COMMENT 'Unidade Primária de Amostragem',
	`Estrato` VARCHAR(7) NULL COMMENT 'Estrato',
	`V1008` VARCHAR(2) NULL COMMENT 'Número de seleção do domicílio',
	`V1014` VARCHAR(2) NULL COMMENT 'Painel',
	`V1023` VARCHAR(1) NULL COMMENT 'Tipo de área',
	`V1027` DECIMAL(18,5) NULL COMMENT 'Peso SEM pós estratificação',
	`V1028` DECIMAL(18,5) NULL COMMENT 'Peso COM pós estratificação',
	`V1029` INT NULL COMMENT 'Projeção da população do trim.',
	`posest` VARCHAR(3) NULL COMMENT 'Domínios de projeção',
	`V2001` INT NULL COMMENT 'Número de pessoas no domicílio',
	`V2003` VARCHAR(2) NULL COMMENT 'Número de ordem',
	`V2005` VARCHAR(2) NULL COMMENT 'Condição no domicílio',
	`V2007` VARCHAR(1) NULL COMMENT 'Sexo',
	`V2008` VARCHAR(2) NULL COMMENT 'Dia de nascimento',
	`V20081` VARCHAR(2) NULL COMMENT 'Mês de nascimento',
	`V20082` VARCHAR(4) NULL COMMENT 'Ano de nascimento',
	`V2009` INT NULL COMMENT 'Idade na data de referência',
	`V3001` VARCHAR(1) NULL COMMENT 'Sabe ler e escrever',
	`V3002` VARCHAR(1) NULL COMMENT 'Frequenta escola',
	`V3002A` VARCHAR(1) NULL COMMENT 'A escola que ... frequenta é de',
	`V3003` VARCHAR(2) NULL COMMENT 'Qual é o curso que frequenta',
	`V3003A` VARCHAR(2) NULL COMMENT 'Qual é o curso que frequenta',
	`V3004` VARCHAR(1) NULL COMMENT 'Duração deste curso que requenta',
	`V3005` VARCHAR(1) NULL COMMENT 'Curso que frequenta é seriado',
	`V3005A` VARCHAR(1) NULL COMMENT 'Curso que freq é organizado em:',
	`V3006` VARCHAR(2) NULL COMMENT 'Qual é o ano série que frequenta',
	`V3007` VARCHAR(1) NULL COMMENT 'Concluiu outro curso de graduação',
	`V3008` VARCHAR(1) NULL COMMENT 'Anteriormente frequentou escola',
	`V3009` VARCHAR(2) NULL COMMENT 'Curso mais elevado que frequentou',
	`V3009A` VARCHAR(2) NULL COMMENT 'Curso mais elevado que frequentou',
	`V3010` VARCHAR(1) NULL COMMENT 'Duração do curso que frequentou',
	`V3011` VARCHAR(1) NULL COMMENT 'Curso quefrequentou era seriado',
	`V3011A` VARCHAR(1) NULL COMMENT 'Curso que freq é organizado em:',
	`V3012` VARCHAR(1) NULL COMMENT 'Aprovado na prim. série do curso',
	`V3013` VARCHAR(2) NULL COMMENT 'Último ano série que concluiu',
	`V3014` VARCHAR(1) NULL COMMENT 'Concluiu o curso que frequentou',
	`V4001` VARCHAR(1) NULL COMMENT 'Trabalhou 1 hr em ativ. remunerd.',
	`V4002` VARCHAR(1) NULL COMMENT 'Trabalhou 1 hr em produtos etc...',
	`V4003` VARCHAR(1) NULL COMMENT 'Fez algum bico pelo menos de 1 hr',
	`V4004` VARCHAR(1) NULL COMMENT 'Ajudou sem receber no domic. 1 hr',
	`V4005` VARCHAR(1) NULL COMMENT 'Afastado trabalho remunerado',
	`V4006` VARCHAR(1) NULL COMMENT 'Motivo de estar afastado',
	`V4006A` VARCHAR(1) NULL COMMENT 'Motivo de estar afastado',
	`V4007` VARCHAR(1) NULL COMMENT 'Durante afastameno recebia pagam.',
	`V4008` VARCHAR(1) NULL COMMENT 'Quanto tempo que estava afastado',
	`V40081` VARCHAR(2) NULL COMMENT 'Tempo de afastamenento até 1 ano',
	`V40082` VARCHAR(2) NULL COMMENT 'Tempo de afastamen. de 1 a 2 anos',
	`V40083` VARCHAR(2) NULL COMMENT 'Tempo de afastamen. mais d 2 anos',
	`V4009` VARCHAR(1) NULL COMMENT 'Quantos trabalhos tinhana semana',
	`V4010` VARCHAR(4) NULL COMMENT 'Ocupação no trab. principal',
	`V4012` VARCHAR(1) NULL COMMENT 'Posição na ocupação',
	`V40121` VARCHAR(1) NULL COMMENT 'Tipo trabalhador não remunerado',
	`V4013` VARCHAR(5) NULL COMMENT 'Atividade no trab. principal',
	`V40132` VARCHAR(1) NULL COMMENT 'Seção da atividade',
	`V40132A` VARCHAR(1) NULL COMMENT 'Seção da atividade',
	`V4028` VARCHAR(1) NULL COMMENT 'Servidor público estatutário',
	`V4029` VARCHAR(1) NULL COMMENT 'Carteira de trabalho assinada',
	`V4033` VARCHAR(1) NULL COMMENT 'Rendimento habitual var. auxil.',
	`V40331` VARCHAR(1) NULL COMMENT 'Rendimento habitual em dinheiro',
	`V403311` VARCHAR(1) NULL COMMENT 'Faixa do valor do rendimento hab.',
	`V403312` INT NULL COMMENT 'Valor do rend. hab. em dinheiro',
	`V40332` VARCHAR(1) NULL COMMENT 'Rendimento habitual em produtos',
	`V403321` VARCHAR(1) NULL COMMENT 'Faixa do valor do rendimento hab.',
	`V403322` INT NULL COMMENT 'Valor do rend. hab. em produtos',
	`V40333` VARCHAR(1) NULL COMMENT 'Rendimento habitual em benefícios',
	`V4034` VARCHAR(1) NULL COMMENT 'Rendimento efetivo var. auxil.',
	`V40341` VARCHAR(1) NULL COMMENT 'Rendimento efetivo em dinheiro',
	`V403411` VARCHAR(1) NULL COMMENT 'Faixa do valor do rendimento efe.',
	`V403412` INT NULL COMMENT 'Valor do rend. efe. em dinheiro',
	`V40342` VARCHAR(1) NULL COMMENT 'Rendimento efetivo em produtos',
	`V403421` VARCHAR(1) NULL COMMENT 'Faixa do valor do rendimento efe.',
	`V403422` INT NULL COMMENT 'Valor do rend. efe. em produtos',
	`V4050` VARCHAR(1) NULL COMMENT 'Rendimento habitual var. auxil.',
	`V40501` VARCHAR(1) NULL COMMENT 'Rendimento habitual em dinheiro',
	`V405011` VARCHAR(1) NULL COMMENT 'Faixa do valor do rendimento hab.',
	`V405012` INT NULL COMMENT 'Valor do rend. hab. em dinheiro',
	`V40502` VARCHAR(1) NULL COMMENT 'Rendimento habitual em produtos',
	`V405021` VARCHAR(1) NULL COMMENT 'Faixa do valor do rendimento hab.',
	`V405022` INT NULL COMMENT 'Valor do rend. hab. em produtos',
	`V40503` VARCHAR(1) NULL COMMENT 'Rendimento habitual em benefícios',
	`V4051` VARCHAR(1) NULL COMMENT 'Rendimento efetivo var. auxil.',
	`V40511` VARCHAR(1) NULL COMMENT 'Rendimento efetivo em dinheiro',
	`V405111` VARCHAR(1) NULL COMMENT 'Faixa do valor do rendimento efe.',
	`V405112` INT NULL COMMENT 'Valor do rend. efe. em dinheiro',
	`V40512` VARCHAR(1) NULL COMMENT 'Rendimento efetivo em produtos',
	`V405121` VARCHAR(1) NULL COMMENT 'Faixa do valor do rendimento efe.',
	`V405122` INT NULL COMMENT 'Valor do rend. efe. em produtos',
	`V4058` VARCHAR(1) NULL COMMENT 'Rendimento habitual var. auxil.',
	`V40581` VARCHAR(1) NULL COMMENT 'Rendimento habitual em dinheiro',
	`V405811` VARCHAR(1) NULL COMMENT 'Faixa do valor do rendimento hab.',
	`V405812` INT NULL COMMENT 'Valor do rend. hab. em dinheiro',
	`V40582` VARCHAR(1) NULL COMMENT 'Rendimento habitual em produtos',
	`V405821` VARCHAR(1) NULL COMMENT 'Faixa do valor do rendimento hab.',
	`V405822` INT NULL COMMENT 'Valor do rend. hab. em produtos',
	`V40583` VARCHAR(1) NULL COMMENT 'Rendimento habitual em benefícios',
	`V40584` VARCHAR(1) NULL COMMENT 'Não remunerado',
	`V4059` VARCHAR(1) NULL COMMENT 'Rendimento efetivo var. auxil.',
	`V40591` VARCHAR(1) NULL COMMENT 'Rendimento efetivo em dinheiro',
	`V405911` VARCHAR(1) NULL COMMENT 'Faixa do valor do rendimento efe.',
	`V405912` INT NULL COMMENT 'Valor do rend. efe. em dinheiro',
	`V40592` VARCHAR(1) NULL COMMENT 'Rendimento efetivo em produtos',
	`V405921` VARCHAR(1) NULL COMMENT 'Faixa do valor do rendimento efe.',
	`V405922` INT NULL COMMENT 'Valor do rend. efe. em produtos',
	`V4071` VARCHAR(1) NULL COMMENT 'Providência p conseg. trab.(30d)',
	`V4072` VARCHAR(2) NULL COMMENT 'Principal provid. p conseg. trab.',
	`V4072A` VARCHAR(1) NULL COMMENT 'Principal provid. p/conseg. trab.',
	`V4073` VARCHAR(1) NULL COMMENT 'Gostaria de ter trabalhado',
	`V4074A` VARCHAR(2) NULL COMMENT 'Motivo de não ter tomado provid.',
	`V4074` VARCHAR(1) NULL COMMENT 'Motivo de não ter tomado provid.',
	`V4077` VARCHAR(1) NULL COMMENT 'Poderia ter começado a trabalhar',
	`V4078` VARCHAR(1) NULL COMMENT 'Motivo p ñ querer começar a trab.',
	`V4078A` VARCHAR(1) NULL COMMENT 'Motivo p/ñ querer/começar a trab.',
	`VD2003` INT NULL COMMENT 'Número de componentes do domic.',
	`VD3001` VARCHAR(1) NULL COMMENT 'Nível de instrução',
	`VD4001` VARCHAR(1) NULL COMMENT 'Condição em relação força d trab.',
	`VD4002` VARCHAR(1) NULL COMMENT 'Condição de ocupação',
	`VD4007` VARCHAR(1) NULL COMMENT 'Posição na ocupação trab. princ.',
	`VD4008` VARCHAR(1) NULL COMMENT 'Posição na ocupação trab. princ.',
	`VD4009` VARCHAR(2) NULL COMMENT 'Posição na ocupação trab. princ.',
	`VD4010` VARCHAR(2) NULL COMMENT 'Grupamen. d ativid. trab. princ.',
	`VD4011` VARCHAR(2) NULL COMMENT 'Grupamen. ocupacion. trab. Princ.',
	`VD4015` VARCHAR(1) NULL COMMENT 'Tipo d remuneração trab. princ.',
	`VD4016` INT NULL COMMENT 'Rendim. habitual trab. princ.',
	`VD4017` INT NULL COMMENT 'Rendim. efetivo trab. princ.',
	`VD4018` VARCHAR(1) NULL COMMENT 'Tipo d remuneração em qq trabalho',
	`VD4019` INT NULL COMMENT 'Rendim. habitual qq trabalho',
	`VD4020` INT NULL COMMENT 'Rendim. efetivo qq trabalho',
	`VD4023` VARCHAR(1) NULL COMMENT 'Pq ñ proc. ñ gost. ñ disp.p trab.',
	`VD4030` VARCHAR(1) NULL COMMENT 'Pq ñ proc./ñ gost./ñ disp.p/trab.'
) ENGINE = InnoDB CHARACTER SET latin1 COLLATE latin1_general_ci;